<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


## Name-Subham Kedia
## UNI-sk4355
## Assignment-4b

### Imports

In [1]:
import datetime
import numpy as np
import pandas as pd
%matplotlib inline
import pandas_datareader.data as web
import fix_yahoo_finance as yf
import sys

In [2]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    arr = np.arange(1,n+1)
    fact = np.prod(arr)
    return fact
        
factorial(6)

720

In [3]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    arr1 = np.arange(1,n+1)
    factorial_array = np.cumprod(arr1)
    return factorial_array

all_factorials(6)

array([  1,   2,   6,  24, 120, 720])

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [4]:
def get_pct_changes(file_name):
    arr = np.genfromtxt(file_name, delimiter=",")
    arr = arr[:,1]
    arr = arr[~np.isnan(arr)]
    difference = np.diff(arr)
    pct_change = np.repeat(0.0, len(difference))
    for i in range(0, len(pct_change)):
        pct_change[i] = difference[i]/arr[i]
    return pct_change
    
get_pct_changes('Class 4 - GS.csv')

array([-0.01253447, -0.00520435,  0.03185746, -0.00094815, -0.00070372,
       -0.008285  , -0.00664159, -0.00063073, -0.00042079, -0.01279674,
       -0.00260106, -0.0085503 , -0.00733042, -0.00894841,  0.00078899,
        0.00398547, -0.00588905,  0.00438808,  0.02922803,  0.00772558,
       -0.00867733])

In [5]:
get_pct_changes('Class 4 - GS.csv')

array([-0.01253447, -0.00520435,  0.03185746, -0.00094815, -0.00070372,
       -0.008285  , -0.00664159, -0.00063073, -0.00042079, -0.01279674,
       -0.00260106, -0.0085503 , -0.00733042, -0.00894841,  0.00078899,
        0.00398547, -0.00588905,  0.00438808,  0.02922803,  0.00772558,
       -0.00867733])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [6]:
datafile = "Class 4 - GS.csv"
import pandas as pd
df = pd.read_csv('Class 4 - GS.csv', na_values='null')
df_close = df['Adj Close']
df['one-day percent change'] = np.repeat(0.0, len(df_close))
df['one-day percent change'] = df_close.pct_change()

def GroupColFunc(df, ind, col):
    if df[col].loc[ind] > 0.025 and df[col].loc[ind] > 0:
        return 'High+'
    elif df[col].loc[ind] <= 0.025 and df[col].loc[ind] > 0:
        return 'Low+'
    elif df[col].loc[ind] >= -0.025:
        return 'Low-'
    elif df[col].loc[ind] < -0.025:
        return 'High-'
    
grouped = df.groupby(lambda x: GroupColFunc(df, x, 'one-day percent change'))
grouped
print(grouped.size())
print(grouped.mean())

High+     2
Low+      4
Low-     15
dtype: int64
        Adj Close  one-day percent change
High+  238.689628                0.030543
Low+   230.965000                0.004222
Low-   235.148258               -0.006011


In [7]:
def GroupColFunc(df, ind, col):
    if df[col].loc[ind] > 0.025 and df[col].loc[ind] > 0:
        return 'High+'
    elif df[col].loc[ind] <= 0.025 and df[col].loc[ind] > 0:
        return 'Low+'
    elif df[col].loc[ind] >= -0.025:
        return 'Low-'
    elif df[col].loc[ind] < -0.025:
        return 'High-'

In [8]:
grouped = df.groupby(lambda x: GroupColFunc(df, x, 'one-day percent change'))
grouped
print(grouped.size())
print(grouped.mean())

High+     2
Low+      4
Low-     15
dtype: int64
        Adj Close  one-day percent change
High+  238.689628                0.030543
Low+   230.965000                0.004222
Low-   235.148258               -0.006011
